#!/bin/bash

# Tailscale Setup Instructions
# This script provides instructions for setting up Tailscale on your Vultr VM

echo "=== Tailscale Setup Guide ==="
echo ""
echo "To enable Tailscale integration:"
echo ""
echo "1. Create a Tailscale Auth Key:"
echo "   - Visit: https://login.tailscale.com/admin/settings/keys"
echo "   - Click 'Generate auth key'"
echo "   - Set it to be REUSABLE (if you want) or EPHEMERAL (recommended for security)"
echo "   - Set expiration time as needed"
echo "   - Copy the generated key (starts with 'tskey-auth-...')"
echo ""
echo "2. Add the key to your .env file:"
echo "   TS_AUTHKEY=tskey-auth-YOUR_KEY_HERE"
echo ""
echo "3. Uncomment the tailscale service in docker-compose.prod.yml:"
echo "   - Remove the '#' comments from the tailscale service block"
echo "   - Uncomment the volumes section at the bottom"
echo ""
echo "4. Restart your services:"
echo "   docker compose -f docker-compose.prod.yml up -d"
echo ""
echo "5. Verify Tailscale is running:"
echo "   docker compose -f docker-compose.prod.yml logs tailscale"
echo ""
echo "6. Check your Tailscale admin console to see the new node appear"
echo ""
echo "7. Access your services via Tailscale DNS:"
echo "   - Backend: http://vultr-node:8000"
echo "   - Headless: http://vultr-node:8001"
echo "   - Video: http://vultr-node:8002"
echo ""
echo "IMPORTANT:"
echo "- Never commit TS_AUTHKEY to git - it should only be in .env"
echo "- Use ephemeral keys for better security"
echo "- The Tailscale container will appear in your Tailscale admin console"
echo ""
